### ISSUE TITLE
Little issue on solution file

### ISSUE THREAD

**Issue by GibbOne** [asm-jaime/TDDCByVisualStudio#1]
Thx a lot for your response on [stackoverflow](https://stackoverflow.com/questions/71673838/is-it-possible-to-use-visual-studio-2022-test-explorer-to-run-c-unit-test/72123111#72123111) and for this example!

Just a little fix from my side.

![image](https://user-images.githubusercontent.com/12271500/167125573-612ea5e1-e2ef-47d7-bb7e-34f2d3078f85.png)

Solution file has wrong paths for project files.

Bye!

**Comment by asm-jaime** [comment]
Thanks. Fixed.
